# Datasource configuration in dev environment
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
  datasource:
    url: jdbc:postgresql://localhost:5432/tour_of_heroes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: monsolis
